language: erlang

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1 ZMQ_VER=4.1
    - LUA=lua5.2 ZMQ_VER=4.1
    - LUA=lua5.3 ZMQ_VER=4.1
    - LUA=luajit ZMQ_VER=4.1

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - bash .travis/setup_sodium.sh
  - bash .travis/setup_zmq.sh

install:
  - if [ $LUA = "luajit" ]; then
      sudo luarocks install https://raw.github.com/moteus/lzmq/master/rockspecs/lzmq-ffi-scm-0.rockspec;
    else
      sudo luarocks install https://raw.github.com/moteus/lzmq/master/rockspecs/lzmq-scm-0.rockspec;
    fi

  - sudo luarocks install lunitx
  - sudo luarocks install lua-path
  - sudo luarocks install luafilesystem --from=https://rocks.moonscript.org/dev
  - sudo luarocks install lua-llthreads2
  - sudo luarocks make rockspecs/lzmq-auth-scm-0.rockspec

script:
  - cd test
  - lunit.sh test_cert.lua
  - lunit.sh test_auth.lua

notifications:
  email:
    on_success: change
    on_failure: always